ARG arch=amd64

FROM ${arch}/node:12-alpine AS builder

RUN apk add --no-cache g++ make pkgconf python

RUN mkdir -p /app
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM ${arch}/node:12-alpine

COPY --from=builder /app /app/

EXPOSE 8888
WORKDIR /app
ENTRYPOINT ["npm"]
CMD ["start"]
