ARG arch=amd64

FROM ${arch}/node:14-buster AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y build-essential python

RUN mkdir -p /app
WORKDIR /app
COPY . .
RUN npm install --no-save
RUN npm run build


FROM ${arch}/node:14-buster-slim

COPY --from=builder /app /app/

EXPOSE 8888
WORKDIR /app
ENTRYPOINT ["npm"]
CMD ["start"]
