ARG arch=amd64
FROM ${arch}/node:14-alpine AS builder

WORKDIR /app
RUN apk add --no-cache g++ make pkgconf python
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build


FROM ${arch}/node:14-alpine

WORKDIR /app
COPY --from=builder /app .

EXPOSE 8888

ENTRYPOINT ["npm"]
CMD ["start"]
