FROM node:14-buster AS builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y build-essential python
WORKDIR /app
COPY . .
RUN npm run all-install
RUN npm run build

FROM node:14-buster-slim
LABEL maintainer="l3tnun"
COPY --from=builder /app /app/
EXPOSE 8888
WORKDIR /app
ENTRYPOINT ["npm"]
CMD ["start"]
