import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';

import { MYSQL_MIGRATION_CASE_TIMEOUT_MS } from './backend-runtime';
import { createOperator, type TestLogger } from './harness';
import {
    MYSQL_FIXTURE_LIFECYCLE_TIMEOUT_MS,
    provisionMySql,
    type MySqlRuntime,
    type MysqlSchema,
    type SslOnlyUser,
} from './mysql-runtime';

const logger = (): TestLogger => ({ system: { error: vi.fn(), info: vi.fn() } });

/** サーバーの CA とは無関係に作った自己署名の CA 証明書（検証に失敗することを確かめるためだけに使う）。 */
const UNRELATED_CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBojCCAUmgAwIBAgIUUqKGlS9Aym8FYd588vWItVyuYmQwCgYIKoZIzj0EAwIw
JjEkMCIGA1UEAwwbU3ludGhldGljIFVucmVsYXRlZCBUZXN0IENBMCAXDTI2MTAw
ODIyNTgyOFoYDzIxMjYwOTE0MjI1ODI4WjAmMSQwIgYDVQQDDBtTeW50aGV0aWMg
VW5yZWxhdGVkIFRlc3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARSSVpB
wOGVJRgkMyOKVOgNlfYgIaVTBiyukp88cBkfQOlWhcOr9Ht+q9M+z+n9pbBsx0+M
WQQfuAk+M5yA+ucRo1MwUTAdBgNVHQ4EFgQUOR9gK9svCbQKxeaFejDzMA9lsK0w
HwYDVR0jBBgwFoAUOR9gK9svCbQKxeaFejDzMA9lsK0wDwYDVR0TAQH/BAUwAwEB
/zAKBggqhkjOPQQDAgNHADBEAiAi1B1SwUPlaH9mWxnrdElX+LW0eaehcdseQuzJ
n+D0sQIgaJUBcUO07jHzVSDmjzW0CKFlwlbF8bfxzls5/GGpJNY=
-----END CERTIFICATE-----`;

let mysqlRuntime: MySqlRuntime;
let schema: MysqlSchema;
let sslUser: SslOnlyUser;
let serverCa: string;

beforeAll(async () => {
    mysqlRuntime = await provisionMySql();
    schema = await mysqlRuntime.createSchema();
    sslUser = await mysqlRuntime.createSslOnlyUser(schema.config.database);
    serverCa = await mysqlRuntime.readCaCertificate();
}, MYSQL_FIXTURE_LIFECYCLE_TIMEOUT_MS);

afterAll(async () => {
    await mysqlRuntime?.cleanup();
}, MYSQL_FIXTURE_LIFECYCLE_TIMEOUT_MS);

const mysqlConfig = (ssl?: unknown) => ({
    dbtype: 'mysql',
    mysql: {
        database: schema.config.database,
        host: schema.config.host,
        port: schema.config.port,
        ...sslUser.login,
        ...(typeof ssl === 'undefined' ? {} : { ssl }),
    },
});

const failureOf = async (config: Record<string, unknown>): Promise<unknown> => {
    const operator = createOperator(config, logger());
    return operator.getConnection().then(
        () => undefined,
        (error: unknown) => error,
    );
};

describe('DBOperator MySQL TLS connection integration (the server CA auto-generated by MySQL 8.4)', () => {
    it(
        '[PERSIST-1.4-MYSQL-SSL-CONNECT] connects a REQUIRE SSL user over TLS when ssl.ca is the server CA',
        async () => {
            expect(serverCa).toContain('BEGIN CERTIFICATE');
            const operator = createOperator(mysqlConfig({ ca: serverCa }), logger());
            const source = await operator.getConnection();
            try {
                expect(source.isInitialized).toBe(true);
                const rows = (await source.query("SHOW SESSION STATUS LIKE 'Ssl_cipher'")) as Array<{ Value: string }>;
                expect(rows[0]?.Value).not.toBe('');
                await expect(operator.checkConnection()).resolves.toBeUndefined();
            } finally {
                await operator.closeConnection();
            }
        },
        MYSQL_MIGRATION_CASE_TIMEOUT_MS,
    );

    it('[PERSIST-1.4-MYSQL-SSL-REQUIRED] refuses the REQUIRE SSL user when ssl is omitted', async () => {
        const failure = await failureOf(mysqlConfig());

        expect(failure).toBeInstanceOf(Error);
        expect((failure as { code?: string }).code).toBe('ER_ACCESS_DENIED_ERROR');
    });

    it('[PERSIST-1.4-MYSQL-SSL-WRONG-CA] refuses the server certificate when ssl.ca is an unrelated CA', async () => {
        const failure = await failureOf(mysqlConfig({ ca: UNRELATED_CA_PEM }));

        expect(failure).toBeInstanceOf(Error);
        // mysql2 は TLS の検証の失敗を HANDSHAKE_SSL_ERROR として返し、message に証明書の検証の失敗を書く。
        expect((failure as { code?: string }).code).toBe('HANDSHAKE_SSL_ERROR');
        expect((failure as Error).message).toMatch(/self[- ]signed certificate|unable to verify/iu);
    });

    it(
        'releases the isolated MySQL fixture container after every case of the file',
        async () => {
            // 利用者と schema は container ごと消える。
            await mysqlRuntime.cleanup();
        },
        MYSQL_FIXTURE_LIFECYCLE_TIMEOUT_MS,
    );
});
