import { SETTINGS_UI_CONTRACT } from '@/shared/settings'
import type { SettingsControlDefinition } from './settingsControlTypes'
import { rangeOptions, valueOptions } from './lib/settingsControlOptions'

/** 録画 / 検索 / ルール / ビデオプレーヤ の control 定義（表示順）。 */
export const SETTINGS_CONTROL_ROWS_BACK = [
  {
    section: '録画',
    label: '表示件数',
    key: 'recordedLength',
    controlType: 'select',
    options: rangeOptions(
      SETTINGS_UI_CONTRACT.recordedLength.min,
      SETTINGS_UI_CONTRACT.recordedLength.max,
      '件',
    ),
    range: {
      min: SETTINGS_UI_CONTRACT.recordedLength.min,
      max: SETTINGS_UI_CONTRACT.recordedLength.max,
      step: 1,
    },
    tmpTarget: 'recordedLength',
  },
  {
    section: '録画',
    label: 'テーブル表示',
    key: 'isShowTableMode',
    controlType: 'switch',
    tmpTarget: 'isShowTableMode',
  },
  {
    section: '録画',
    label: 'ドロップ情報を表示する',
    subtitle: '概要の代わりにドロップとファイルサイズ情報を表示する',
    key: 'isShowDropInfoInsteadOfDescription',
    controlType: 'switch',
    tmpTarget: 'isShowDropInfoInsteadOfDescription',
  },
  {
    section: '録画',
    label: '削除時のチェックを入れるか',
    subtitle: '有効にするとファイル削除のチェックが入れられた状態で録画削除ダイアログが開かれます',
    key: 'deleteRecordedDefaultValue',
    controlType: 'switch',
    tmpTarget: 'deleteRecordedDefaultValue',
  },
  {
    section: '録画',
    label: 'web での再生を優先する',
    key: 'isPreferredPlayingOnWeb',
    controlType: 'switch',
    tmpTarget: 'isPreferredPlayingOnWeb',
  },
  {
    section: '録画',
    label: '視聴 URL Scheme',
    key: 'shouldUseRecordedViewURLScheme',
    controlType: 'switch',
    tmpTarget: 'shouldUseRecordedViewURLScheme',
  },
  {
    section: '録画',
    label: '視聴 URL Scheme',
    key: 'recordedViewURLScheme',
    controlType: 'text',
    tmpTarget: 'recordedViewURLScheme',
  },
  {
    section: '録画',
    label: 'ダウンロード URL Scheme',
    key: 'shouldUseRecordedDownloadURLScheme',
    controlType: 'switch',
    tmpTarget: 'shouldUseRecordedDownloadURLScheme',
  },
  {
    section: '録画',
    label: 'ダウンロード URL Scheme',
    key: 'recordedDownloadURLScheme',
    controlType: 'text',
    tmpTarget: 'recordedDownloadURLScheme',
  },
  {
    section: '検索',
    label: '最大表示件数',
    key: 'searchLength',
    controlType: 'select',
    options: valueOptions(SETTINGS_UI_CONTRACT.searchLength.values, '件'),
    range: {
      min: 50,
      max: 600,
      step: 50,
    },
    tmpTarget: 'searchLength',
  },
  {
    section: '検索',
    label: '自動スクロール',
    subtitle: 'ルール編集時に検索結果へ自動スクロールする',
    key: 'isEnableAutoScrollWhenEditingRule',
    controlType: 'switch',
    tmpTarget: 'isEnableAutoScrollWhenEditingRule',
  },
  {
    section: '検索',
    label: '自動サブディレクトリ設定',
    subtitle: 'ルール作成時にキーワードをサブディレクトリにコピーする',
    key: 'isEnableCopyKeywordToDirectory',
    controlType: 'switch',
    tmpTarget: 'isEnableCopyKeywordToDirectory',
  },
  {
    section: '検索',
    label: '録画済み番組を排除',
    subtitle: 'ルール作成時に録画済み番組を排除をチェックする',
    key: 'isCheckAvoidDuplicate',
    controlType: 'switch',
    tmpTarget: 'isCheckAvoidDuplicate',
  },
  {
    section: '検索',
    label: 'エンコードの自動設定',
    subtitle: 'ルール作成時にエンコード設定を自動で行う',
    key: 'isEnableEncodingSettingWhenCreateRule',
    controlType: 'switch',
    tmpTarget: 'isEnableEncodingSettingWhenCreateRule',
  },
  {
    section: '検索',
    label: '元ファイルの自動削除',
    subtitle: 'ルール作成時に元ファイルの自動削除をチェックする',
    key: 'isCheckDeleteOriginalAfterEncode',
    controlType: 'switch',
    tmpTarget: 'isCheckDeleteOriginalAfterEncode',
  },
  {
    section: 'ルール',
    label: '表示件数',
    key: 'rulesLength',
    controlType: 'select',
    options: rangeOptions(
      SETTINGS_UI_CONTRACT.rulesLength.min,
      SETTINGS_UI_CONTRACT.rulesLength.max,
      '件',
    ),
    range: {
      min: SETTINGS_UI_CONTRACT.rulesLength.min,
      max: SETTINGS_UI_CONTRACT.rulesLength.max,
      step: 1,
    },
    tmpTarget: 'rulesLength',
  },
  {
    section: 'ルール',
    label: '拡張ページネーションの有効化',
    subtitle: 'ルール一覧で先頭・最終ページへの移動とページ数の入力ができるページネーションを使う',
    key: 'isEnableExtendedPagination',
    controlType: 'switch',
    tmpTarget: 'isEnableExtendedPagination',
  },
  {
    section: 'ビデオプレーヤ',
    label: '字幕の縁取りを強制する',
    subtitle: 'aribb24.js 使用時に有効になります',
    key: 'isForceEnableSubtitleStroke',
    controlType: 'switch',
    tmpTarget: 'isForceEnableSubtitleStroke',
  },
] as const satisfies readonly SettingsControlDefinition[]
