export type RouteMethod = 'del' | 'get' | 'post' | 'put';
export type ContractGroup = 'media' | 'recorded' | 'scheduling';

export interface RequestFixture {
    readonly body?: Record<string, unknown>;
    readonly file?: Record<string, unknown>;
    readonly headers?: Record<string, string>;
    readonly params?: Record<string, string>;
    readonly query?: Record<string, unknown>;
}

export interface RouteContractCase {
    readonly body: unknown;
    readonly contentType: string;
    readonly file: string;
    readonly group: ContractGroup;
    readonly method: RouteMethod;
    readonly ownerArgs: readonly unknown[];
    readonly ownerMethod: string;
    readonly ownerResult: unknown;
    readonly ownerToken: string;
    readonly request: RequestFixture;
    readonly status: number;
}

const json = (
    group: ContractGroup,
    file: string,
    method: RouteMethod,
    ownerToken: string,
    ownerMethod: string,
    request: RequestFixture,
    ownerArgs: readonly unknown[],
    ownerResult: unknown,
    status: number,
    body: unknown,
): RouteContractCase => ({
    body,
    contentType: 'application/json',
    file,
    group,
    method,
    ownerArgs,
    ownerMethod,
    ownerResult,
    ownerToken,
    request,
    status,
});

const binary = (
    group: ContractGroup,
    file: string,
    ownerToken: string,
    ownerMethod: string,
    request: RequestFixture,
    ownerArgs: readonly unknown[],
    ownerResult: unknown,
    contentType: string,
    body: unknown,
): RouteContractCase => ({
    body,
    contentType,
    file,
    group,
    method: 'get',
    ownerArgs,
    ownerMethod,
    ownerResult,
    ownerToken,
    request,
    status: 200,
});

const halfWidth = false;
const listResult = [{ id: 501, name: 'synthetic-result' }];
const itemResult = { id: 502, name: 'synthetic-item' };
const reserveBody = { allowEndLack: false, programId: 12 };
const ruleBody = {
    isTimeSpecification: false,
    reserveOption: { allowEndLack: false, avoidDuplicate: false, enable: true },
    searchOption: { keyword: 'synthetic-rule' },
};

export const schedulingRouteCases: readonly RouteContractCase[] = [
    json('scheduling', 'channels', 'get', 'IChannelApiModel', 'getChannels', {}, [], listResult, 200, listResult),
    binary(
        'scheduling',
        'channels/{channelId}/logo',
        'IChannelApiModel',
        'getLogo',
        { params: { channelId: '11' } },
        [11],
        Buffer.from('synthetic-logo'),
        'image/png',
        'synthetic-logo',
    ),
    json(
        'scheduling',
        'schedules',
        'get',
        'IScheduleApiModel',
        'getSchedules',
        {
            query: {
                BS: true,
                BS4K: true,
                CS: false,
                GR: true,
                SKY: false,
                endAt: '2000',
                isFree: true,
                isHalfWidth: halfWidth,
                needsRawExtended: true,
                startAt: '1000',
            },
        },
        [
            {
                BS: true,
                BS4K: true,
                CS: false,
                GR: true,
                SKY: false,
                endAt: 2000,
                isFree: true,
                isHalfWidth: halfWidth,
                needsRawExtended: true,
                startAt: 1000,
            },
        ],
        listResult,
        200,
        listResult,
    ),
    json(
        'scheduling',
        'schedules/broadcasting',
        'get',
        'IScheduleApiModel',
        'getBroadcastingSchedule',
        { query: { isHalfWidth: halfWidth, time: '3000' } },
        [{ isHalfWidth: halfWidth, time: 3000 }],
        listResult,
        200,
        listResult,
    ),
    json(
        'scheduling',
        'schedules/detail/{programId}',
        'get',
        'IScheduleApiModel',
        'getSchedule',
        { params: { programId: '12' }, query: { isHalfWidth: halfWidth } },
        [12, halfWidth],
        itemResult,
        200,
        itemResult,
    ),
    json(
        'scheduling',
        'schedules/search',
        'post',
        'IScheduleApiModel',
        'search',
        { body: { isHalfWidth: halfWidth, limit: 9, option: { keyword: 'synthetic-keyword' } } },
        [{ keyword: 'synthetic-keyword' }, halfWidth, 9],
        listResult,
        200,
        listResult,
    ),
    json(
        'scheduling',
        'schedules/{channelId}',
        'get',
        'IScheduleApiModel',
        'getChannelSchedule',
        {
            params: { channelId: '11' },
            query: { days: '2', isFree: true, isHalfWidth: halfWidth, needsRawExtended: true, startAt: '1000' },
        },
        [
            {
                channelId: 11,
                days: 2,
                isFree: true,
                isHalfWidth: halfWidth,
                needsRawExtended: true,
                startAt: 1000,
            },
        ],
        listResult,
        200,
        listResult,
    ),
    json(
        'scheduling',
        'reserves',
        'get',
        'IReserveApiModel',
        'gets',
        { query: { isHalfWidth: halfWidth, limit: '10', offset: '3', ruleId: '14', type: 'normal' } },
        [{ isHalfWidth: halfWidth, limit: 10, offset: 3, ruleId: 14, type: 'normal' }],
        listResult,
        200,
        listResult,
    ),
    json('scheduling', 'reserves', 'post', 'IReserveApiModel', 'add', { body: reserveBody }, [reserveBody], 13, 201, {
        reserveId: 13,
    }),
    json('scheduling', 'reserves/cnts', 'get', 'IReserveApiModel', 'getCnts', {}, [], itemResult, 200, itemResult),
    json(
        'scheduling',
        'reserves/lists',
        'get',
        'IReserveApiModel',
        'getLists',
        { query: { endAt: '2000', startAt: '1000' } },
        [{ endAt: 2000, startAt: 1000 }],
        itemResult,
        200,
        itemResult,
    ),
    json('scheduling', 'reserves/update', 'post', 'IReserveApiModel', 'updateAll', {}, [], undefined, 200, {
        code: 200,
    }),
    json(
        'scheduling',
        'reserves/{reserveId}',
        'get',
        'IReserveApiModel',
        'get',
        { params: { reserveId: '13' }, query: { isHalfWidth: halfWidth } },
        [13, halfWidth],
        itemResult,
        200,
        itemResult,
    ),
    json(
        'scheduling',
        'reserves/{reserveId}',
        'del',
        'IReserveApiModel',
        'cancel',
        { params: { reserveId: '13' } },
        [13],
        { canceled: true },
        200,
        { canceled: true },
    ),
    json(
        'scheduling',
        'reserves/{reserveId}',
        'put',
        'IReserveApiModel',
        'edit',
        { body: reserveBody, params: { reserveId: '13' } },
        [13, reserveBody],
        undefined,
        201,
        { code: 201, message: 'ok' },
    ),
    json(
        'scheduling',
        'reserves/{reserveId}/overlap',
        'del',
        'IReserveApiModel',
        'removeOverlap',
        { params: { reserveId: '13' } },
        [13],
        { removed: 'overlap' },
        200,
        { removed: 'overlap' },
    ),
    json(
        'scheduling',
        'reserves/{reserveId}/skip',
        'del',
        'IReserveApiModel',
        'removeSkip',
        { params: { reserveId: '13' } },
        [13],
        { removed: 'skip' },
        200,
        { removed: 'skip' },
    ),
    json(
        'scheduling',
        'rules',
        'get',
        'IRuleApiModel',
        'gets',
        { query: { keyword: 'synthetic-keyword', limit: '10', offset: '3', type: 'normal' } },
        [{ keyword: 'synthetic-keyword', limit: 10, offset: 3, type: 'normal' }],
        listResult,
        200,
        listResult,
    ),
    json('scheduling', 'rules', 'post', 'IRuleApiModel', 'add', { body: ruleBody }, [ruleBody], 14, 201, {
        ruleId: 14,
    }),
    json(
        'scheduling',
        'rules/keyword',
        'get',
        'IRuleApiModel',
        'searchKeyword',
        { query: { keyword: 'synthetic-keyword', limit: '10', offset: '3' } },
        [{ keyword: 'synthetic-keyword', limit: 10, offset: 3 }],
        listResult,
        200,
        { items: listResult },
    ),
    json('scheduling', 'rules/keyword', 'post', 'IRuleApiModel', 'add', { body: ruleBody }, [ruleBody], 14, 201, {
        ruleId: 14,
    }),
    json(
        'scheduling',
        'rules/{ruleId}',
        'get',
        'IRuleApiModel',
        'get',
        { params: { ruleId: '14' } },
        [14],
        itemResult,
        200,
        itemResult,
    ),
    json(
        'scheduling',
        'rules/{ruleId}',
        'del',
        'IRuleApiModel',
        'delete',
        { params: { ruleId: '14' } },
        [14],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'scheduling',
        'rules/{ruleId}',
        'put',
        'IRuleApiModel',
        'update',
        { body: ruleBody, params: { ruleId: '14' } },
        [{ ...ruleBody, id: 14 }],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'scheduling',
        'rules/{ruleId}/disable',
        'put',
        'IRuleApiModel',
        'disable',
        { params: { ruleId: '14' } },
        [14],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'scheduling',
        'rules/{ruleId}/enable',
        'put',
        'IRuleApiModel',
        'enable',
        { params: { ruleId: '14' } },
        [14],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'scheduling',
        'recording',
        'get',
        'IRecordingApiModel',
        'gets',
        {
            query: {
                channelId: '11',
                genre: '5',
                isHalfWidth: halfWidth,
                isReverse: 'true',
                keyword: 'synthetic-keyword',
                limit: '10',
                offset: '3',
                ruleId: '14',
            },
        },
        [
            {
                channelId: 11,
                genre: 5,
                isHalfWidth: halfWidth,
                isReverse: 'true',
                keyword: 'synthetic-keyword',
                limit: 10,
                offset: 3,
                ruleId: 14,
            },
        ],
        listResult,
        200,
        listResult,
    ),
    json('scheduling', 'recording/resettimer', 'post', 'IRecordingApiModel', 'resetTimer', {}, [], undefined, 200, {
        code: 200,
    }),
] as const;

const recordedQuery = {
    channelId: '11',
    genre: '5',
    hasOriginalFile: true,
    isHalfWidth: halfWidth,
    isReverse: true,
    keyword: 'synthetic-keyword',
    limit: '10',
    offset: '3',
    ruleId: '14',
};
const recordedOptions = {
    channelId: 11,
    genre: 5,
    hasOriginalFile: true,
    isHalfWidth: halfWidth,
    isReverse: true,
    keyword: 'synthetic-keyword',
    limit: 10,
    offset: 3,
    ruleId: 14,
};
const uploadedBody = {
    fileType: 'ts',
    parentDirectoryName: 'primary',
    recordedId: 12,
    subDirectory: 'child',
    viewName: 'synthetic-view',
};

export const recordedRouteCases: readonly RouteContractCase[] = [
    json(
        'recorded',
        'recorded',
        'get',
        'IRecordedApiModel',
        'gets',
        { query: recordedQuery },
        [recordedOptions],
        listResult,
        200,
        listResult,
    ),
    json(
        'recorded',
        'recorded',
        'post',
        'IRecordedApiModel',
        'createNewRecorded',
        { body: { channelId: 11, endAt: 2000, name: 'synthetic-recorded', startAt: 1000 } },
        [{ channelId: 11, endAt: 2000, name: 'synthetic-recorded', startAt: 1000 }],
        12,
        201,
        { recordedId: 12 },
    ),
    json('recorded', 'recorded/cleanup', 'post', 'IRecordedApiModel', 'fileCleanup', {}, [], undefined, 200, {
        code: 200,
    }),
    json(
        'recorded',
        'recorded/options',
        'get',
        'IRecordedApiModel',
        'getSearchOptionList',
        {},
        [],
        itemResult,
        200,
        itemResult,
    ),
    json(
        'recorded',
        'recorded/{recordedId}',
        'get',
        'IRecordedApiModel',
        'get',
        { params: { recordedId: '12' }, query: { isHalfWidth: halfWidth } },
        [12, halfWidth],
        itemResult,
        200,
        itemResult,
    ),
    json(
        'recorded',
        'recorded/{recordedId}',
        'del',
        'IRecordedApiModel',
        'delete',
        { params: { recordedId: '12' } },
        [12],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'recorded/{recordedId}/encode',
        'del',
        'IRecordedApiModel',
        'stopEncode',
        { params: { recordedId: '12' } },
        [12],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'recorded/{recordedId}/protect',
        'put',
        'IRecordedApiModel',
        'changeProtect',
        { params: { recordedId: '12' } },
        [12, true],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'recorded/{recordedId}/unprotect',
        'put',
        'IRecordedApiModel',
        'changeProtect',
        { params: { recordedId: '12' } },
        [12, false],
        undefined,
        200,
        { code: 200 },
    ),
    // src/model/service/api/videos/upload.ts calls
    // container.get<IIPCClient>('IIPCClient').uploadedVideoRegistrationPort.dispatch(option)
    // (see src/model/ipc/IUploadedVideoRegistration.ts), not a flat
    // owner[ownerMethod](...args) call. ownerToken/ownerArgs/status/body below
    // are still consumed generically (inventory count, exhaustiveness,
    // request fixture), but route-runtime.spec.test.ts and
    // integration/service-interface.integration.test.ts special-case
    // file === 'videos/upload' for the disposition-shaped owner call itself.
    json(
        'recorded',
        'videos/upload',
        'post',
        'IIPCClient',
        'uploadedVideoRegistrationPort',
        {
            body: uploadedBody,
            file: { originalname: 'synthetic.ts', path: 'synthetic-upload-path' },
        },
        [
            {
                fileName: 'synthetic.ts',
                filePath: 'synthetic-upload-path',
                fileType: 'ts',
                parentDirectoryName: 'primary',
                recordedId: 12,
                subDirectory: 'child',
                viewName: 'synthetic-view',
            },
        ],
        undefined,
        200,
        { code: 200, result: 'ok' },
    ),
    binary(
        'recorded',
        'videos/{videoFileId}',
        'IVideoApiModel',
        'getFullFilePath',
        { params: { videoFileId: '22' }, query: { isDownload: false } },
        [22],
        { mime: 'video/mp2t', path: '$fixture' },
        'video/mp2t',
        'synthetic-resource',
    ),
    json(
        'recorded',
        'videos/{videoFileId}',
        'del',
        'IVideoApiModel',
        'deleteVideoFile',
        { params: { videoFileId: '22' } },
        [22],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'videos/{videoFileId}/duration',
        'get',
        'IVideoApiModel',
        'getDuration',
        { params: { videoFileId: '22' } },
        [22],
        1234,
        200,
        { duration: 1234 },
    ),
    json(
        'recorded',
        'videos/{videoFileId}/kodi',
        'post',
        'IVideoApiModel',
        'sendToKodi',
        {
            body: { kodiName: 'living-room' },
            headers: { host: 'receiver.invalid:8443', 'x-forwarded-proto': 'https' },
            params: { videoFileId: '22' },
        },
        ['receiver.invalid:8443', true, 'living-room', 22],
        undefined,
        200,
        { code: 200 },
    ),
    {
        ...binary(
            'recorded',
            'videos/{videoFileId}/playlist',
            'IVideoApiModel',
            'getM3u8',
            {
                headers: {
                    host: 'receiver.invalid:8443',
                    'user-agent': 'synthetic-agent',
                    'x-forwarded-proto': 'https',
                },
                params: { videoFileId: '22' },
            },
            ['receiver.invalid:8443', true, 22],
            { name: 'synthetic.m3u8', playList: '#EXTM3U\n./streamfiles/stream81.m3u8' },
            'application/x-mpegURL',
            '#EXTM3U\n./streamfiles/stream81.m3u8',
        ),
    },
    json('recorded', 'thumbnails', 'post', 'IThumbnailApiModel', 'regenerate', {}, [], undefined, 200, {
        code: 200,
    }),
    json('recorded', 'thumbnails/cleanup', 'post', 'IThumbnailApiModel', 'fileCleanup', {}, [], undefined, 200, {
        code: 200,
    }),
    json(
        'recorded',
        'thumbnails/videos/{videoFileId}',
        'post',
        'IThumbnailApiModel',
        'add',
        { params: { videoFileId: '22' } },
        [22],
        undefined,
        200,
        { code: 200 },
    ),
    binary(
        'recorded',
        'thumbnails/{thumbnailId}',
        'IThumbnailApiModel',
        'getIdFilePath',
        { params: { thumbnailId: '31' } },
        [31],
        '$fixture',
        'image/jpeg',
        'synthetic-resource',
    ),
    json(
        'recorded',
        'thumbnails/{thumbnailId}',
        'del',
        'IThumbnailApiModel',
        'delete',
        { params: { thumbnailId: '31' } },
        [31],
        undefined,
        200,
        { code: 200 },
    ),
    binary(
        'recorded',
        'dropLogs/{dropLogFileId}',
        'IDropLogApiModel',
        'getIdFilePath',
        { params: { dropLogFileId: '32' }, query: { maxsize: '4096' } },
        [32, 4096],
        '$fixture',
        'text/plain',
        'synthetic-resource',
    ),
    json(
        'recorded',
        'tags',
        'get',
        'IRecordedTagApiModel',
        'gets',
        { query: { excludeTagId: ['7', '8'], limit: '10', name: 'synthetic-tag', offset: '3' } },
        [{ excludeTagId: [7, 8], limit: 10, name: 'synthetic-tag', offset: 3 }],
        listResult,
        200,
        listResult,
    ),
    json(
        'recorded',
        'tags',
        'post',
        'IRecordedTagApiModel',
        'create',
        { body: { color: '#123456', name: 'synthetic-tag' } },
        ['synthetic-tag', '#123456'],
        7,
        201,
        { tagId: 7 },
    ),
    json(
        'recorded',
        'tags/{tagId}',
        'del',
        'IRecordedTagApiModel',
        'delete',
        { params: { tagId: '7' } },
        [7],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'tags/{tagId}',
        'put',
        'IRecordedTagApiModel',
        'update',
        { body: { color: '#654321', name: 'synthetic-updated-tag' }, params: { tagId: '7' } },
        [7, 'synthetic-updated-tag', '#654321'],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'tags/{tagId}/relate',
        'del',
        'IRecordedTagApiModel',
        'deleteRelation',
        { params: { tagId: '7' }, query: { recordedId: '12' } },
        [7, 12],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'recorded',
        'tags/{tagId}/relate',
        'put',
        'IRecordedTagApiModel',
        'setRelation',
        { body: { recordedId: 12 }, params: { tagId: '7' } },
        [7, 12],
        undefined,
        200,
        { code: 200 },
    ),
] as const;

export const mediaRouteCases: readonly RouteContractCase[] = [
    json(
        'media',
        'encode',
        'get',
        'IEncodeApiModel',
        'getAll',
        { query: { isHalfWidth: halfWidth } },
        [halfWidth],
        listResult,
        200,
        listResult,
    ),
    json(
        'media',
        'encode',
        'post',
        'IEncodeApiModel',
        'add',
        { body: { mode: 'mobile', recordedId: 12, removeOriginal: false, sourceVideoFileId: 22 } },
        [{ mode: 'mobile', recordedId: 12, removeOriginal: false, sourceVideoFileId: 22 }],
        91,
        201,
        { encodeId: 91 },
    ),
    json(
        'media',
        'encode/{encodeId}',
        'del',
        'IEncodeApiModel',
        'cancel',
        { params: { encodeId: '91' } },
        [91],
        undefined,
        200,
        { code: 200 },
    ),
    json('media', 'storages', 'get', 'IStorageApiModel', 'getInfo', {}, [], itemResult, 200, itemResult),
    json(
        'media',
        'streams',
        'get',
        'IStreamApiModel',
        'getStreamInfos',
        { query: { isHalfWidth: halfWidth } },
        [halfWidth],
        listResult,
        200,
        listResult,
    ),
    json('media', 'streams', 'del', 'IStreamApiModel', 'stopAll', {}, [], undefined, 200, { code: 200 }),
    json(
        'media',
        'streams/{streamId}',
        'del',
        'IStreamApiModel',
        'stop',
        { params: { streamId: '81' } },
        [81],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'media',
        'streams/{streamId}/keep',
        'put',
        'IStreamApiModel',
        'keep',
        { params: { streamId: '81' } },
        [81],
        undefined,
        200,
        { code: 200 },
    ),
    json(
        'media',
        'streams/live/{channelId}/hls',
        'get',
        'IStreamApiModel',
        'startLiveHLSStream',
        { params: { channelId: '11' }, query: { mode: '2' } },
        [{ channelId: 11, mode: 2 }],
        81,
        200,
        { streamId: 81 },
    ),
    {
        ...binary(
            'media',
            'streams/live/{channelId}/m2ts/playlist',
            'IStreamApiModel',
            'getLiveM2TsStreamM3u8',
            {
                headers: {
                    host: 'receiver.invalid:8443',
                    'user-agent': 'synthetic-agent',
                    'x-forwarded-proto': 'https',
                },
                params: { channelId: '11' },
                query: { mode: '2' },
            },
            ['receiver.invalid:8443', true, { channelId: 11, mode: 2 }],
            { name: 'synthetic-live.m3u8', playList: '#EXTM3U\nhttps://receiver.invalid/live.ts' },
            'application/x-mpegURL',
            '#EXTM3U\nhttps://receiver.invalid/live.ts',
        ),
    },
    json(
        'media',
        'streams/recorded/{videoFileId}/hls',
        'get',
        'IStreamApiModel',
        'startRecordedHLSStream',
        { params: { videoFileId: '22' }, query: { mode: '2', ss: '15' } },
        [{ mode: 2, playPosition: 15, videoFileId: 22 }],
        82,
        200,
        { streamId: 82 },
    ),
] as const;

export interface StreamRouteCase {
    readonly contentType: string;
    readonly file: string;
    readonly ownerArgs: readonly unknown[];
    readonly ownerMethod: string;
    readonly request: RequestFixture;
}

export const streamRouteCases: readonly StreamRouteCase[] = [
    {
        contentType: 'video/mp2t',
        file: 'streams/live/{channelId}/m2ts',
        ownerArgs: [{ channelId: 11, mode: 2 }],
        ownerMethod: 'startLiveM2TsStream',
        request: { params: { channelId: '11' }, query: { mode: '2' } },
    },
    {
        contentType: 'video/mp2t',
        file: 'streams/live/{channelId}/m2tsll',
        ownerArgs: [{ channelId: 11, mode: 2 }],
        ownerMethod: 'startLiveM2TsLLStream',
        request: { params: { channelId: '11' }, query: { mode: '2' } },
    },
    {
        contentType: 'video/mp4',
        file: 'streams/live/{channelId}/mp4',
        ownerArgs: [{ channelId: 11, mode: 2 }],
        ownerMethod: 'startMp4Stream',
        request: { params: { channelId: '11' }, query: { mode: '2' } },
    },
    {
        contentType: 'video/webm',
        file: 'streams/live/{channelId}/webm',
        ownerArgs: [{ channelId: 11, mode: 2 }],
        ownerMethod: 'startLiveWebmStream',
        request: { params: { channelId: '11' }, query: { mode: '2' } },
    },
    {
        contentType: 'video/mp4',
        file: 'streams/recorded/{videoFileId}/mp4',
        ownerArgs: [{ mode: 2, playPosition: 15, videoFileId: 22 }],
        ownerMethod: 'startRecordedMp4Stream',
        request: { params: { videoFileId: '22' }, query: { mode: '2', ss: '15' } },
    },
    {
        contentType: 'video/webm',
        file: 'streams/recorded/{videoFileId}/webm',
        ownerArgs: [{ mode: 2, playPosition: 15, videoFileId: 22 }],
        ownerMethod: 'startRecordedWebMStream',
        request: { params: { videoFileId: '22' }, query: { mode: '2', ss: '15' } },
    },
] as const;

export const allRouteCases = [...schedulingRouteCases, ...recordedRouteCases, ...mediaRouteCases] as const;

export const operationKey = ({ file, method }: Pick<RouteContractCase, 'file' | 'method'>): string =>
    `${method.toUpperCase()} /${file}`;
